version: '3.8'

services:
  jenkins:
    networks:
      - cicd-pipelines
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${myname}/Documents/secure-cicd-pipeline/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sockss

  jenkins-agent:
    networks:
      - cicd-pipelines
    image: jenkins/ssh-agent:alpine-jdk17

networks:
  cicd-pipelines: {}